### ISSUE TITLE
Add `prymer` to bioconda

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/prymer#5]
See: https://github.com/bioconda/bioconda-recipes/pull/50249

**Comment by msto** [comment]
The linked pull request was merged.

https://github.com/bioconda/bioconda-recipes/pull/50249

The bioconda recipe does not include `bwa-interactive` - I am not sure if we want to tie that to this issue, or close this and open another.

**Comment by clintval** [comment]
I discovered the recipe on bioconda is shipping a _**non-interactive**_ version of bwa. See here for more information and next steps:

https://github.com/fulcrumgenomics/prymer/pull/32#issuecomment-2362821429
